services:
  - type: web
    name: inky-tombola-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PRIVATE_KEY
        sync: false